---
name: Main Script

on:
  workflow_dispatch:

jobs:
  run-main-script:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install Python 3.12
        run: uv python install 3.12
      - name: Run our main script
        run: uv run --with rich main.py
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]