name: Main Script
on:
  workflow_dispatch: null
jobs:
  run-main-script:
    name: Run on Windows self-hosted
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run our main script
        env:
          PYTHONIOENCODING: utf8
        run: uv run --with rich main.py
