name: Main Script
on:
  workflow_dispatch: null
jobs:
  run-main-script:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install Python 3.12
        run: uv python install 3.12
      - name: Run our main script
        run: uv run --with rich main.py
