name: Main Script Windows-self-hosted
on:
  workflow_dispatch: null
jobs:
  run-main-script:
    name: Run on Windows self-hosted
    runs-on: self-hosted
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Run our main script
        env:
          PYTHONIOENCODING: utf8
        run: uv run --with rich main.py
