name: Main Script
on:
  workflow_dispatch: null
jobs:
  run-main-script:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest too costly
    name: Run on ${{ matrix.os }}
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install Python 3.11
        run: uv python install 3.11
      - name: Run our main script
        env:
          PYTHONIOENCODING: utf8
        run: uv run --with rich main.py
